/**
 * This class was automatically generated by using the new JPA Entities from Tables.
 */
package com.example.model;

import java.io.Serializable;

import javax.persistence.*;

import java.sql.Timestamp;

/**
 * SharedBuying is the persistent class for the sharedbuying database table.
 * @author Georgios Skourletopoulos
 * @version 4 August 2013
 */
@Entity
@NamedQuery(name="Sharedbuying.findAll", query="SELECT s FROM SharedBuying s")
public class SharedBuying implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private String id;

	@ManyToOne
	@JoinColumn(name="buyingId")
	private TDinBuying buyingId;

	private Timestamp dateShared;

	@ManyToOne
	@JoinColumn(name="fromUserId")    //uni-directional many-to-one association to UserLogin
	private UserLogin fromUserId;

	@ManyToOne
	@JoinColumn(name="toUserId")    //uni-directional many-to-one association to UserLogin
	private UserLogin toUserId;

	public SharedBuying() {}    //implicit constructor

	/**
	 * The explicit contructor that is used to create the shared TD for Leasing estimate object.
	 * @param fromUserId the sender's ID
	 * @param toUserId the receiver's ID
	 * @param buyingId the estimation ID
	 * @param dateShared the sharing date
	 */
	public SharedBuying(UserLogin fromUserId, UserLogin toUserId, TDinBuying buyingId, Timestamp dateShared) {
		this.fromUserId = fromUserId;
		this.toUserId = toUserId;
		this.buyingId = buyingId;
		this.dateShared = dateShared;
	}

	/**
	 * Getter for the sharing ID (transaction - insert ID)
	 * @return this.id as a String
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Setter for the sharing ID (transaction - insert ID)
	 * @param id the new ID to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Getter for the estimation's ID
	 * @return this.buyingId as a TDinBuying object
	 */
	public TDinBuying getBuyingId() {
		return this.buyingId;
	}

	/**
	 * Setter for the estimation's ID
	 * @param buyingId the new Leasing ID to set
	 */
	public void setBuyingId(TDinBuying buyingId) {
		this.buyingId = buyingId;
	}

	/**
	 * Getter for the estimation's sharing date
	 * @return this.dateShared as a Timestamp object
	 */
	public Timestamp getDateShared() {
		return this.dateShared;
	}

	/**
	 * Setter for the estimation's sharing date
	 * @param dateShared the new sharing date to set
	 */
	public void setDateShared(Timestamp dateShared) {
		this.dateShared = dateShared;
	}

	/**
	 * Getter for the sender's ID
	 * @return this.fromUserId as a UserLogin object
	 */
	public UserLogin getFromUserId() {
		return this.fromUserId;
	}

	/**
	 * Setter for the sender's ID
	 * @param fromUserId the new sender's ID to set
	 */
	public void setFromUserId(UserLogin fromUserId) {
		this.fromUserId = fromUserId;
	}

	/**
	 * Getter for the receiver's ID
	 * @return this.toUserId as a UserLogin object
	 */
	public UserLogin getToUserId() {
		return this.toUserId;
	}

	/**
	 * Setter for the receiver's ID
	 * @param toUserId the new receiver's ID to set
	 */
	public void setToUserId(UserLogin toUserId) {
		this.toUserId = toUserId;
	}

	/**
	 * Redefining the equality between two SharedBuying objects. 
	 */
	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof SharedBuying)) {
			return false;
		}
		final SharedBuying sb = (SharedBuying) o;
		if (!fromUserId.equals(sb.getFromUserId())) {
			return false;
		}
		else if (!toUserId.equals(sb.getFromUserId()))
			return false;
		else if (!buyingId.equals(sb.getBuyingId()))
			return false;
		return true;
	}

	/**
	 * Redefining the hash code of a SharedBuying object.
	 * @return buyingId.hashCode() + fromUserId.hashCode() + toUserId.hashCode(), the hash code of the object
	 */
	@Override
	public int hashCode() {
		if (buyingId != null) {
			return (buyingId.hashCode() + fromUserId.hashCode() + toUserId.hashCode());
		}
		return 0;
	}
}
