/**
 * This class was automatically generated by using the new JPA Entities from Tables.
 */
package com.example.model;

import java.io.Serializable;

import javax.persistence.*;

import java.sql.Timestamp;

/**
 * SharedImplementing is the persistent class for the sharedimplementing database table.
 * @author Georgios Skourletopoulos
 * @version 6 August 2013
 */
@Entity
@NamedQuery(name="Sharedimplementing.findAll", query="SELECT s FROM SharedImplementing s")
public class SharedImplementing implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private String id;

	private Timestamp dateShared;

	@ManyToOne
	@JoinColumn(name="implementingId")
	private CostForImplementing implementingId;

	@ManyToOne
	@JoinColumn(name="fromUserId")    //uni-directional many-to-one association to Userlogin
	private UserLogin fromUserId;

	@ManyToOne
	@JoinColumn(name="toUserId")    //uni-directional many-to-one association to Userlogin
	private UserLogin toUserId;

	public SharedImplementing() {}    //implicit constructor

	/**
	 * The explicit contructor that is used to create the shared cost for Implementing estimate object.
	 * @param fromUserId the sender's ID
	 * @param toUserId the receiver's ID
	 * @param implementingId the estimation ID
	 * @param dateShared the sharing date
	 */
	public SharedImplementing(UserLogin fromUserId, UserLogin toUserId, CostForImplementing implementingId,
			Timestamp dateShared) {
		this.fromUserId = fromUserId;
		this.toUserId = toUserId;
		this.implementingId = implementingId;
		this.dateShared = dateShared;
	}

	/**
	 * Getter for the sharing ID (transaction - insert ID)
	 * @return this.id as a String
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Setter for the sharing ID (transaction - insert ID)
	 * @param id the new ID to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Getter for the estimation's sharing date
	 * @return this.dateShared as a Timestamp object
	 */
	public Timestamp getDateShared() {
		return this.dateShared;
	}

	/**
	 * Setter for the estimation's sharing date
	 * @param dateShared the new sharing date to set
	 */
	public void setDateShared(Timestamp dateShared) {
		this.dateShared = dateShared;
	}

	/**
	 * Getter for the estimation's ID
	 * @return this.implementingId as a CostForImplementing object
	 */
	public CostForImplementing getImplementingId() {
		return this.implementingId;
	}

	/**
	 * Setter for the estimation's ID
	 * @param implementingId the new Implementing ID to set
	 */
	public void setImplementingId(CostForImplementing implementingId) {
		this.implementingId = implementingId;
	}

	/**
	 * Getter for the sender's ID
	 * @return this.fromUserId as a UserLogin object
	 */
	public UserLogin getFromUserId() {
		return this.fromUserId;
	}

	/**
	 * Setter for the sender's ID
	 * @param fromUserId the new sender's ID to set
	 */
	public void setFromUserId(UserLogin fromUserId) {
		this.fromUserId = fromUserId;
	}

	/**
	 * Getter for the receiver's ID
	 * @return this.toUserId as a UserLogin object
	 */
	public UserLogin getToUserId() {
		return this.toUserId;
	}

	/**
	 * Setter for the receiver's ID
	 * @param toUserId the new receiver's ID to set
	 */
	public void setToUserId(UserLogin toUserId) {
		this.toUserId = toUserId;
	}

	/**
	 * Redefining the equality between two SharedImplementing objects. 
	 */
	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof SharedImplementing)) {
			return false;
		}
		final SharedImplementing si = (SharedImplementing) o;
		if (!fromUserId.equals(si.getFromUserId())) {
			return false;
		}
		else if (!toUserId.equals(si.getFromUserId()))
			return false;
		else if (!implementingId.equals(si.getImplementingId()))
			return false;
		return true;
	}

	/**
	 * Redefining the hash code of a SharedImplementing object.
	 * @return implementingId.hashCode() + fromUserId.hashCode() + toUserId.hashCode(), the hash code of the object
	 */
	@Override
	public int hashCode() {
		if (implementingId != null) {
			return (implementingId.hashCode() + fromUserId.hashCode() + toUserId.hashCode());
		}
		return 0;
	}
}
